# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/wahoo/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter taimen walleye,$(TARGET_DEVICE)),)

endif
